[workspace]
members = ["crates/ecs", "crates/parser"]

[package]
name = "compiler_proj"
version = "0.1.0"
edition = "2024"

[dependencies]
ecs = { workspace = true }
parser = {workspace = true }
parser_types = { workspace = true }
parser_macros = { workspace = true }
graphviz-rust = "0.9.6"
clap = {version = "4.5.54", features=["derive"]}
raylib = "5.5"

[workspace.dependencies]
typed-generational-arena = "0.2"
ecs = { path = "./crates/ecs" }
parser = { path = "./crates/parser" }
parser_macros = { path = "./crates/parser/parser_macros" }
parser_types = { path = "./crates/parser/parser_types" }
graphviz-rust = "0.9.6"
