[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
annotate-snippets = "0.12.9"
thiserror = "2.0.17"
derivative = "2.2.0"
typed-generational-arena = { workspace = true }
ecs = { workspace = true }
graphviz-rust = { workspace = true }
rand = "0.10.0-rc.5"
parser_types = { workspace = true }
parser_macros = { workspace = true }
